// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Model capability modes that may be selected after thread creation.
 *
 * `isolated` is intentionally absent because that mode is creation-only and
 * immutable for the lifetime of its bounded thread.
 */
export type TurnModelToolMode = "default" | "disabled";
