// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceContextClip = { id: string, version: string, derivativeId: string, documentId: string, clientId: string, encounterId: string | null, noteId: string | null, kind: string, title: string, body: string, reviewStatus: string, sourceMethod: string, pageRange: string, timestampRange: string, lineRange: string, segmentLabel: string, tags: string, metadataJson: string, archivedAt: number | null, createdAt: number, updatedAt: number, };
