// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspacePlanActiveRun } from "./WorkspacePlanActiveRun";
import type { WorkspacePlanMessage } from "./WorkspacePlanMessage";
import type { WorkspacePlanRevision } from "./WorkspacePlanRevision";
import type { WorkspacePlanSession } from "./WorkspacePlanSession";
import type { WorkspacePlanTurnCompletionReceipt } from "./WorkspacePlanTurnCompletionReceipt";

export type WorkspacePlanRecoveryState = { session: WorkspacePlanSession, activeRuns: Array<WorkspacePlanActiveRun>, pendingQuestions: Array<WorkspacePlanMessage>, currentRevision: WorkspacePlanRevision | null, lastCompletion: WorkspacePlanTurnCompletionReceipt | null, };
