// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceDraftCheckpoint } from "./WorkspaceDraftCheckpoint";
import type { WorkspaceDraftSessionStatus } from "./WorkspaceDraftSessionStatus";

export type WorkspaceDraftSession = { id: string, clientId: string, status: WorkspaceDraftSessionStatus, currentRevision: number, currentCheckpoint: WorkspaceDraftCheckpoint, createdBy: string, createdAt: number, updatedAt: number, closedAt: number | null, };
