// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceNote = { id: string, clientId: string, encounterId: string | null, title: string, kind: string, body: string, status: string, currentRevision: number, archivedAt: number | null, createdAt: number, updatedAt: number, };
