// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceNoteProposalStatus } from "./WorkspaceNoteProposalStatus";

export type WorkspaceNoteProposal = { id: string, noteId: string, baseRevision: number, proposedBody: string, summary: string, status: WorkspaceNoteProposalStatus, sourceThreadId: string | null, sourceTurnId: string | null, createdAt: number, resolvedAt: number | null, };
