// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceNoteProposalDecisionKind } from "./WorkspaceNoteProposalDecisionKind";

/**
 * Append-only record of what a clinician did with proposed agent work.
 */
export type WorkspaceNoteProposalDecision = { id: string, proposalId: string, agentResultId: string | null, noteId: string, baseRevision: number, decisionKind: WorkspaceNoteProposalDecisionKind, changeId: string | null, appliedText: string | null, appliedTextSha256: string | null, resultingNoteRevision: number | null, actor: string, reason: string | null, createdAt: number, };
