// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelToolMode } from "../ModelToolMode";
import type { JsonValue } from "../serde_json/JsonValue";
import type { WorkspaceGuideRunStatus } from "./WorkspaceGuideRunStatus";

export type WorkspaceGuideRun = { id: string, clientId: string, sessionId: string, sourceCheckpointId: string, sourceCheckpointRevision: number, sourceCheckpointSha256: string, encounterId: string | null, noteId: string | null, requestSchemaVersion: number, requestEnvelope: JsonValue, requestEnvelopeSha256: string, idempotencyKey: string, trigger: string, actor: string, provider: string, model: string, modelToolMode: ModelToolMode, status: WorkspaceGuideRunStatus, sourceThreadId: string | null, sourceTurnId: string | null, terminalEnvelope: JsonValue | null, terminalEnvelopeSha256: string | null, createdAt: number, updatedAt: number, terminalAt: number | null, isStale: boolean, };
