// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceContextPacket = { id: string, clientId: string, encounterId: string | null, noteId: string | null, humanRequest: string, selectedArtifactIdsJson: string, selectedDerivativeIdsJson: string, selectedClipIdsJson: string, artifactSummary: string, derivativeSummary: string, clipSummary: string, chartContextSummary: string, contextEnvelopeJson: string, contextEnvelopeSha256: string, clinicianActor: string, baseNoteRevision: number | null, authorizedScopeJson: string, expectedOutputKind: string, workspaceProfile: string, planSchemaVersion: number, sourceCheckpointId: string | null, sourceCheckpointSha256: string | null, readinessJson: string, status: string, createdAt: number, sentAt: number, submittedAt: number | null, canceledAt: number | null, updatedAt: number, };
