// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type WorkspaceDraftCheckpoint = { id: string, sessionId: string, clientId: string, encounterId: string | null, noteId: string | null, baseNoteRevision: number | null, schemaVersion: number, revision: number, draft: JsonValue, contentSha256: string, trigger: string, actor: string, createdAt: number, };
