// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspacePlanGuideRunOutcome = { "status": "failed", error_summary: string, } | { "status": "canceled", reason: string, };
