// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceDataClassification } from "./WorkspaceDataClassification";

export type WorkspaceDataPolicyStatus = { schemaVersion: number, dataClassification: WorkspaceDataClassification, classifiedAt: number | null, classifiedBy: string | null, };
