// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Packet-authorized database categories that an active agent run may read.
 * The server derives patient ownership from the run and records every returned
 * record as an immutable source snapshot.
 */
export type WorkspaceAgentContextCategory = "visitHistory" | "progressNotes";
