// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceDocument = { id: string, version: string, clientId: string, encounterId: string | null, title: string, kind: string, localPath: string, notes: string, scope: string, detectedKind: string, mimeType: string | null, fileSizeBytes: bigint | null, modifiedAt: number | null, sha256: string | null, tags: string, sourceLabel: string, existenceStatus: string, metadataJson: string, originalPath: string, referenceKind: string, vaultPath: string, contentSha256: string | null, thumbnailPath: string, thumbnailStatus: string, thumbnailMimeType: string | null, intakeSource: string, importedAt: number | null, archivedAt: number | null, createdAt: number, updatedAt: number, };
