// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceTaskPriority } from "./WorkspaceTaskPriority";
import type { WorkspaceTaskStatus } from "./WorkspaceTaskStatus";

export type WorkspaceTask = { id: string, clientId: string, encounterId: string | null, noteId: string | null, documentId: string | null, title: string, details: string, kind: string, status: WorkspaceTaskStatus, priority: WorkspaceTaskPriority, dueDate: string | null, assignedTo: string | null, completedAt: number | null, archivedAt: number | null, createdAt: number, updatedAt: number, };
