// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspacePlanMessageRole } from "./WorkspacePlanMessageRole";

export type WorkspacePlanMessage = { id: string, planSessionId: string, clientId: string, guideRunId: string, sequence: number, role: WorkspacePlanMessageRole, content: string, contentSha256: string, idempotencyKey: string, sourceCheckpointId: string, sourceCheckpointRevision: number, sourceCheckpointSha256: string, encounterId: string | null, noteId: string | null, sourceThreadId: string | null, sourceTurnId: string | null, createdAt: number, replayed: boolean, };
