// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspacePlanTurnCompletionReceipt = { guideRunId: string, planSessionId: string, clientId: string, idempotencyKey: string, assistantMessageId: string, planRevisionId: string | null, completionInputSha256: string, evidenceManifestSha256: string, evidenceReadCount: number, terminalEnvelopeSha256: string, sourceCheckpointId: string, sourceCheckpointRevision: number, sourceCheckpointSha256: string, sourceThreadId: string, sourceTurnId: string, provider: string, model: string, promptSha256: string, completedAt: number, replayed: boolean, };
