// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceClient } from "./WorkspaceClient";
import type { WorkspaceDocument } from "./WorkspaceDocument";
import type { WorkspaceNote } from "./WorkspaceNote";
import type { WorkspaceNoteSummary } from "./WorkspaceNoteSummary";
import type { WorkspaceTaskSummary } from "./WorkspaceTaskSummary";

export type WorkspaceContext = { client: WorkspaceClient, activeNote: WorkspaceNote | null, recentNotes: Array<WorkspaceNoteSummary>, documents: Array<WorkspaceDocument>, tasks: Array<WorkspaceTaskSummary>, };
