// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceContextPacketReplay = { id: string, clientId: string, encounterId: string | null, noteId: string | null, humanRequest: string, contextEnvelopeJson: string, contextEnvelopeSha256: string, clinicianActor: string, baseNoteRevision: number | null, authorizedScopeJson: string, expectedOutputKind: string, readOnlySafetyConstraints: Array<string>, status: string, sentAt: number, submittedAt: number | null, };
