// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspacePatientSafetyItem = { id: string, clientId: string, category: string, name: string, reaction: string | null, severity: string | null, dose: string | null, route: string | null, frequency: string | null, status: string | null, recordedDate: string | null, notes: string, archivedAt: number | null, createdAt: number, updatedAt: number, };
