// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspacePlanSubmissionReceipt = { planRevisionId: string, packetId: string, agentRunId: string, planSessionId: string, clientId: string, planContentSha256: string, evidenceManifestSha256: string, submittedBy: string, submittedAt: number, };
