// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceTaskPriority } from "./WorkspaceTaskPriority";

export type WorkspacePlanProposalPayload = { "kind": "note_revision", note_id: string, base_revision: number, proposed_body: string, } | { "kind": "note_addendum", note_id: string, base_revision: number, body: string, } | { "kind": "task_draft", title: string, details: string, task_kind: string, priority: WorkspaceTaskPriority, due_date: string | null, assigned_to: string | null, };
