// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One execution attempt against an immutable context packet. Retries create a
 * new run; repeated starts with the same packet/idempotency key return the
 * existing run.
 */
export type WorkspaceAgentRun = { id: string, packetId: string, clientId: string, noteId: string | null, baseNoteRevision: number | null, contextEnvelopeSha256: string, runKind: string, idempotencyKey: string, provider: string | null, model: string | null, sourceThreadId: string | null, sourceTurnId: string | null, status: string, errorSummary: string | null, startedAt: number, completedAt: number | null, createdAt: number, updatedAt: number, };
