// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceDocument } from "./WorkspaceDocument";

export type WorkspacePracticeLibraryItem = { document: WorkspaceDocument, ownerClientId: string, ownerDisplayName: string, linkedToActiveClient: boolean, linkedDocumentId: string | null, scopeReason: string, reviewedTextCount: bigint, clipCount: bigint, };
