// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceEncounter = { id: string, version: string, clientId: string, kind: string, title: string, status: string, startedAt: number | null, endedAt: number | null, archivedAt: number | null, createdAt: number, updatedAt: number, };
