// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspacePlanSessionStatus } from "./WorkspacePlanSessionStatus";

export type WorkspacePlanSession = { id: string, clientId: string, sourceThreadId: string | null, status: WorkspacePlanSessionStatus, latestRevision: number, createdBy: string, createdAt: number, updatedAt: number, closedAt: number | null, replayed: boolean, };
