// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspacePlanGuideRunStatus } from "./WorkspacePlanGuideRunStatus";

export type WorkspacePlanGuideRun = { id: string, clientId: string, draftSessionId: string, sourceCheckpointId: string, sourceCheckpointRevision: number, sourceCheckpointSha256: string, encounterId: string | null, noteId: string | null, requestEnvelopeSha256: string, idempotencyKey: string, trigger: string, provider: string, model: string, status: WorkspacePlanGuideRunStatus, sourceThreadId: string | null, sourceTurnId: string | null, createdAt: number, updatedAt: number, terminalAt: number | null, isStale: boolean, replayed: boolean, };
