// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceAuditEvent = { id: string, entityType: string, entityId: string, action: string, actor: string, actorKind: string, source: string, clientId: string | null, encounterId: string | null, noteId: string | null, documentId: string | null, sourceThreadId: string | null, sourceTurnId: string | null, success: boolean, summary: string, metadataJson: string | null, createdAt: number, };
