// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Exact, immutable record returned to one agent run. The snapshot omits local
 * filesystem paths and is hashed server-side for later audit replay.
 */
export type WorkspaceAgentRunSource = { id: string, runId: string, sourceEntityType: string, sourceEntityId: string, sourceRevision: number | null, displayLabel: string, snapshotJson: string, contentSha256: string, accessPurpose: string, accessedAt: number, };
