// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspacePlanRevisionStatus } from "./WorkspacePlanRevisionStatus";

export type WorkspacePlanRevision = { id: string, planSessionId: string, clientId: string, guideRunId: string, revision: number, planMarkdown: string, decisionsJson: string, openQuestionsJson: string, contentSha256: string, evidenceManifestJson: string, evidenceManifestSha256: string, evidenceReadCount: number, idempotencyKey: string, status: WorkspacePlanRevisionStatus, sourceCheckpointId: string, sourceCheckpointRevision: number, sourceCheckpointSha256: string, encounterId: string | null, noteId: string | null, sourceThreadId: string, sourceTurnId: string, createdAt: number, submittedAt: number | null, replayed: boolean, };
