// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspacePlanGuideRun } from "./WorkspacePlanGuideRun";

export type WorkspacePlanActiveRun = { run: WorkspacePlanGuideRun, planSessionId: string, sourceThreadId: string, sourceTurnId: string, provider: string, model: string, promptSha256: string, contextReadCount: number, claimedAt: number, };
