// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceClient = { id: string, version: string, displayName: string, preferredName: string | null, dateOfBirth: string | null, sexOrGender: string | null, externalId: string | null, recordStartDate: string | null, recordEndDate: string | null, summary: string, primaryPhone: string | null, secondaryPhone: string | null, email: string | null, preferredContactMethod: string | null, emergencyContactName: string | null, emergencyContactRelationship: string | null, emergencyContactPhone: string | null, emergencyContactEmail: string | null, contactNotes: string | null, payerName: string | null, planName: string | null, memberId: string | null, groupNumber: string | null, coverageType: string | null, coverageStatus: string | null, coverageNotes: string | null, archivedAt: number | null, createdAt: number, updatedAt: number, };
