// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceCoverageMatchResult } from "./WorkspaceCoverageMatchResult";
import type { WorkspaceCoverageVerificationSubject } from "./WorkspaceCoverageVerificationSubject";

export type WorkspaceCoverageVerification = { id: string, coverageId: string, clientId: string, sourceDocumentId: string, sourceDocumentVersion: string, sourceDocumentContentSha256: string, comparedSubject: WorkspaceCoverageVerificationSubject, observedFirstName: string | null, observedMiddleName: string | null, observedLastName: string | null, observedSuffix: string | null, observedMemberId: string | null, patientRecordVersion: string, patientVersion: string, coverageVersion: string, matchResult: WorkspaceCoverageMatchResult, mismatchFields: Array<string>, actor: string, contentSha256: string, isStale: boolean, createdAt: number, };
