// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspacePlanProposalPayload } from "./WorkspacePlanProposalPayload";
import type { WorkspacePlanProposalStatus } from "./WorkspacePlanProposalStatus";

export type WorkspacePlanProposal = { id: string, planSessionId: string, planRevisionId: string, clientId: string, guideRunId: string, payload: WorkspacePlanProposalPayload, payloadSha256: string, summary: string, rationale: string, idempotencyKey: string, status: WorkspacePlanProposalStatus, sourceCheckpointId: string, sourceCheckpointRevision: number, sourceCheckpointSha256: string, sourceThreadId: string, sourceTurnId: string, createdAt: number, resolvedAt: number | null, resolvedBy: string | null, replayed: boolean, };
