// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Agent results are review-pending outputs bound to one context packet. The
 * packet id/hash are provenance; clients must not treat result payloads as
 * write, signing, submission, payer-contact, or workspace-wide read authority.
 */
export type WorkspaceAgentResult = { id: string, packetId: string, clientId: string, noteId: string | null, contextEnvelopeSha256: string, body: string, summary: string, status: string, createdAt: number, updatedAt: number, };
