// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Audit projection of an immutable record returned to one agent run. The
 * canonical handoff-prompt snapshot is redacted at the app-server boundary;
 * its `content_sha256` continues to identify the exact durable source record.
 */
export type WorkspaceAgentRunSource = { id: string, runId: string, sourceEntityType: string, sourceEntityId: string, sourceRevision: number | null, displayLabel: string, snapshotJson: string, contentSha256: string, accessPurpose: string, accessedAt: number, };
