// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls which capabilities a regular model sampling turn may use.
 */
export type ModelToolMode = "default" | "disabled" | "isolated";
