// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls whether a regular model sampling turn may discover or call tools.
 */
export type ModelToolMode = "default" | "disabled" | "workspaceContextOnly" | "workspacePlanningOnly";
