// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of evaluating a workflow gate.
 */
export type WorkflowGateStatus = "passed" | "warning" | "waitingForApproval" | "blocked";
