// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Category for a workflow audit event.
 */
export type WorkflowAuditEventKind = "stateChanged" | "toolObserved" | "policyEvaluated" | "approvalRequested" | "approvalResolved" | "blocked";
