// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Human approval checkpoint for a workflow action.
 */
export type WorkflowApprovalCheckpoint = { id: string, label: string, reason: string, action: string, irreversible: boolean, };
