// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowAuditEventKind } from "./WorkflowAuditEventKind";

/**
 * Redacted audit event suitable for local history and UI display.
 */
export type WorkflowAuditEvent = { id: string, kind: WorkflowAuditEventKind, summary: string, createdAtMs?: bigint, metadata?: { [key in string]?: string }, };
