// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowApprovalCheckpoint } from "./WorkflowApprovalCheckpoint";
import type { WorkflowAuditEvent } from "./WorkflowAuditEvent";
import type { WorkflowBoundaryStatus } from "./WorkflowBoundaryStatus";
import type { WorkflowGate } from "./WorkflowGate";
import type { WorkflowStateKind } from "./WorkflowStateKind";

/**
 * Durable, redacted status for one supervised regulated workflow.
 */
export type WorkflowSnapshot = { id: string, title: string, state: WorkflowStateKind, boundaryStatus: WorkflowBoundaryStatus, gates: Array<WorkflowGate>, pendingApproval?: WorkflowApprovalCheckpoint, latestAuditEvent?: WorkflowAuditEvent, };
