// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowGateStatus } from "./WorkflowGateStatus";

/**
 * One policy, safety, or readiness gate evaluated for the workflow.
 */
export type WorkflowGate = { id: string, label: string, status: WorkflowGateStatus, summary?: string, source?: string, };
