// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * High-level lifecycle state for a supervised workflow.
 */
export type WorkflowStateKind = "idle" | "planning" | "running" | "waitingForApproval" | "blocked" | "completed";
